# src/tangle/store/base.py

from typing import Protocol

from tangle.types import Detection, DetectionType, Event


class Store(Protocol):
    def record_detection(self, detection: Detection) -> None: ...
    def record_event(self, event: Event) -> None: ...
    def list_detections(
        self, workflow_id: str, limit: int = 100
    ) -> list[Detection]: ...
    def list_detections_by_type(
        self, dtype: DetectionType, limit: int = 100
    ) -> list[Detection]: ...
    def get_workflow_events(self, workflow_id: str) -> list[Event]: ...
    def stats(self) -> dict[str, int]: ...
    def close(self) -> None: ...
